export const BRONGE_PACKAGE_1 = "BRONGE_PACKAGE_1";
export const BRONGE_PACKAGE_2 = "BRONGE_PACKAGE_2";
export const BRONGE_PACKAGE_3 = "BRONGE_PACKAGE_2";

export const SILVER_PACKAGE_1 = "SILVER_PACKAGE_1";
export const SILVER_PACKAGE_2 = "SILVER_PACKAGE_2";
export const SILVER_PACKAGE_3 = "SILVER_PACKAGE_3";

export const GOLD_PACKAGE_1 = "GOLD_PACKAGE_1";
export const GOLD_PACKAGE_2 = "GOLD_PACKAGE_2";
export const GOLD_PACKAGE_3 = "GOLD_PACKAGE_3";






