export const GET_CAREER_LIST="GET_CAREER_LIST";
export const IS_PAGE_LOAD = "IS_PAGE_LOAD";
export const GET_CAREER_DETAILS = "GET_CAREER_DETAILS";
export const GET_CANDIDATE_INPUT = "GET_CANDIDATE_INPUT";
export const IS_LOADING = "IS_LOADING";
