export const INPUT_SIGNUP_TEXT = "INPUT_SIGNUP_TEXT"
export const CREATE_SUBMIT = "CREATE_SUBMIT"
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN"
export const SET_EMPTY_SIGNUP_FIELD = "SET_EMPTY_SIGNUP_FIELD"