export const INPUT_SIGNUP_TEXT = "INPUT_SIGNUP_TEXT";
export const CREATE_SUBMIT = "CREATE_SUBMIT";
export const REDIRECT_TO_LOGIN = "REDIRECT_TO_LOGIN";
export const REDIRECT_TO_VERIFICATION = "REDIRECT_TO_VERIFICATION";
export const SET_EMPTY_SIGNUP_FIELD = "SET_EMPTY_SIGNUP_FIELD";
export const ALL_HUB_LIST = "ALL_HUB_LIST";
export const GET_DISTRICT_LIST = "GET_DISTRICT_LIST";
